name: update readme

on:
  # run every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # or when i manually trigger it
  workflow_dispatch:

jobs:
  wakatime:
    name: fetch data from wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # configuration
          # see: https://github.com/athul/waka-readme#tweaks
          TIME_RANGE: last_7_days
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: TOML JSON

          COMMIT_MESSAGE: "chore(wakatime): update stats"

  snake:
    name: generate snake game
    runs-on: ubuntu-latest

    steps:
      # todo: move back to main action repo once pr is merged
      # see: https://github.com/Platane/snk/pull/155
      # - name: generate svg
      #   uses: Platane/snk/svg-only@v3
      #   with:
      #     github_user_name: ${{ github.repository_owner }}
      #     outputs: |
      #       dist/ctp-mocha-mauve.svg?color_snake=#cba6f7&color_dots=#313244,#6c7086,#9399b2,#b4befe,#cba6f7&color_progress=#cba6f7
      
      - name: Generate snake SVG using fork
        uses: docker://ghcr.io/isitreallyalive/snk:custom-progress
        with:
          github_user_name: isitreallyalive
          outputs: |
            dist/ctp-mocha-mauve.svg?color_snake=#cba6f7&color_dots=#313244,#6c7086,#9399b2,#b4befe,#cba6f7&color_progress=#cba6f7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: upload svg
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}